---
title: "Blog"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  fields: [date,title,reading-time,description]
page-layout: full
title-block-banner: true
---

Hace mucho tiempo que no te escribía, y de verdad es una de las cosas que más he extrañado: leerte, sin prisa, sin estrés, sin dolor.

Te agradezco por todo y por tanto. Muchas de las cosas que he logrado han sido porque, de una u otra manera, tú has estado ahí para mí, para nosotros. Espero que, por pequeño que haya sido mi aporte en tu vida, también haya traído alegría y provecho, ayudándote a crecer como mujer, como persona y como profesional; en resumen, en toda tu esencia.

A veces siento que es injusto lo que nos toca vivir ahora, justo en uno de los mejores momentos que he tenido y que no puedo compartir plenamente contigo. Desde hace tiempo he soñado con algo más allá de la academia, con algo más sólido contigo.

Créeme que aún no encuentro las palabras para decirte todo lo que quiero. No te estoy terminando, tampoco pidiendo tiempo. Es que lo quiero todo contigo. Pero no puedo forzarte a nada por mis propios deseos egoístas. Créeme cuando te digo que realmente eres mi alma.

Todavía estoy procesando todo lo que he tenido que sacrificar. Sé que no volveré a amar a nadie como a ti, ni nadie me amará como tú lo hiciste. Ya no amanecerá igual, no volveré a ver Interestelar de la misma manera, no sé cuántas cosas cambiarán. Y aun así, sé que no disfruté lo suficiente de nuestra última vez juntos, aunque cada día, cada hora, cada minuto a tu lado los viví intensamente, porque por fin lo único que nos limitaba era el tiempo.

Siempre te amaré hasta el quásar más lejano, incluso cuando el universo siga expandiéndose.

A veces me siento como Vi, a veces como Levi. No digo esto para herirte, al contrario: quiero que seas feliz. Como te lo dije alguna vez, si lo nuestro está destinado a ser, lo será, sin forzarlo y sin tener que esperar a nadie. Quiero que disfrutes de cada día que venga, que conozcas y aprendas cosas nuevas, personas nueas, lugares nuevos, que vivas experiencias únicas.

Si alguna vez hablas de mí, como dice la canción: “que si me nombran, no mires al cielo. Guárdame en ese rincón donde guardas las cosas que fueron tus sueños".

Me siento muy orgulloso de ti. Solo tengo pensamientos lindos cuando pienso en ti, aunque me cueste hablar de nosotros con otros porque me da esa especie de futuralgia.

No me esperes. Te amaré por siempre.